local ChickenEggConfig = {
	["Brown chicken"] = { eggModelName = "EggBrown", price = 1 },
	["White chicken"] = { eggModelName = "Egg", price = 2 },
	["Spotted chicken"] = { eggModelName = "EggSpotted", price = 5 },
	["Black chicken"] = { eggModelName = "EggBlack", price = 10 },
	["Red chicken"] = { eggModelName = "EggRed", price = 25 },
	["Blue chicken"] = { eggModelName = "EggBlue", price = 50 },
	["Green chicken"] = { eggModelName = "EggGreen", price = 100 },
	["Pink chicken"] = { eggModelName = "EggPink", price = 250 },
	["Silver chicken"] = { eggModelName = "EggSilver", price = 500 },
	["Gold chicken"] = { eggModelName = "EggGold", price = 1000 },
	["Emerald chicken"] = { eggModelName = "EggEmerald", price = 2500 },
	["Lapis chicken"] = { eggModelName = "EggLapis", price = 5000 },
	["Ruby chicken"] = { eggModelName = "EggRedstone", price = 10000 },
	["Diamond chicken"] = { eggModelName = "EggDiamond", price = 25000 },
	["Crystal chicken"] = { eggModelName = "EggAmethyst", price = 100000 },
	["Obbie chicken"] = { eggModelName = "EggObbie", price = 300000 },
	["Magma chicken"] = { eggModelName = "EggMagma", price = 1000000 },
}

return ChickenEggConfig