local LuckMultipliers = {
	{
		DisplayName = "x2 Luck",
		Multiplier = 2,
		Icon = "rbxassetid://95181624104935",
	},
	{
		DisplayName = "x4 Luck",
		Multiplier = 4,
		Icon = "rbxassetid://102318023844084",
	},
	{
		DisplayName = "x8 Luck",
		Multiplier = 8,
		Icon = "rbxassetid://131074434764254",
	},
	--[[{
		DisplayName = "x16 Luck",
		Multiplier = 16,
		Icon = "rbxassetid://112902314",
	},]]
}

return LuckMultipliers
