local WheelSpinConfig = {}

WheelSpinConfig.Rewards = {
	[1] = {
		Text = "100 Cash",
		Icon = 100223596709442,
		Chance = 40,
	},
	[2] = {
		Text = "1K Cash",
		Icon = 100223596709442,
		Chance = 30,
	},
	[3] = {
		Text = "10K Cash",
		Icon = 100223596709442,
		Chance = 20,
	},
	[4] = {
		Text = "100K Cash",
		Icon = 100223596709442,
		Chance = 5,
	},
	[5] = {
		Text = "150K Cash",
		Icon = 100223596709442,
		Chance = 5,
	},
}

WheelSpinConfig.StartingSpins = 2
WheelSpinConfig.FreeSpinInterval = 600
WheelSpinConfig.FullSpinDuration = 4
WheelSpinConfig.NumberOfSpins = 4

return WheelSpinConfig